### ISSUE TITLE
[ENH] Support for multiple task-files

### ISSUE THREAD

**Issue by nickgarber** [TxGVNN/project-tasks#3]
For example, I appreciate the option of hiding "tool-kit" files with a leading dot, such that both `tasks.org` and `.tasks.org` would be supported.

**Comment by TxGVNN** [comment]
Thanks for your interest in the project.

I think that is a great idea, when I also have many org files have tasks in a folder or a project. Perhaps we will set a list of task files instead one pattern.

Currently, you can open the file you want and call `M-x project-tasks-current-buffer`

**Comment by TxGVNN** [comment]
I pushed this new feature info [3-enh-support-for-multiple-task-files](https://github.com/TxGVNN/project-tasks/tree/3-enh-support-for-multiple-task-files) branch.

If you have time, could you please test on it.

**Comment by TxGVNN** [comment]
Merged!
