### ISSUE TITLE
[ENH] New Task Type: Task Proxy/Generator

### ISSUE THREAD

**Issue by nickgarber** [TxGVNN/project-tasks#4]
Hiya 👋

A task proxy/generator would provide a listing (in some consumable format), of task data, such that:
  - a task generator that includes something like `make list`, would cause the listing of targets to also be usable from project-tasks.

I don't have any particular constraints around how this is implemented, and may be interested in helping to add it based on your interest/feedback.

Perhaps this is already possible by having `project-tasks` execute and pass control to an interactive task that provides some sort of secondary interactive control.

For reference I use https://pydoit.org/, and GNU Make, and am becoming more curious in https://just.systems/ . So those are the downstream systems I have in mind when I'm describing this. 

Thanks!

PS
- Please don't feel any undo rush to add this. I'm just excited to see this project, and wanted to start a discussion on these ideas.
- I've been slowly iterating on a personal (not-yet-published) project focused on using Org-Mode as a portable runtime that may have synergy with this.

**Comment by TxGVNN** [comment]
Thank you for second suggestion.

It looks some features in the future, but I'm not sure if any packages on MELPA are several that are similar in purpose.
I really don't want to repeat features if we actually have it in the community.

So I think you and me can look around MELPA packages to make sure we don't repeat exist things before we continue to discuss on the detail.

**Comment by nickgarber** [comment]
Sure thing - I took a look about ...

- [searching MELPA for 'task'](https://melpa.org/#/?q=task)
  - [task-runner](https://github.com/emacs-taskrunner/emacs-taskrunner) supports multiple task runners but is abandoned 
- [searching MELPA for 'runner' ](https://melpa.org/#/?q=runner)
  - [emacs-bpr](https://github.com/ilya-babanov/emacs-bpr) does look quite cool, but doesn't provide any form of task discovery or selection. 
  - [imake](https://github.com/tarsius/imake/tree/main) provides a navigable list of actions by parsing a`Makefile` for targets to run. The project seems healthy and active though my attempt to use it was unsuccessful. It's `make`-specific but perhaps it could provide inspiration be adapted here, (or for me to create an analogous package for initiating `doit` targets).

I can't claim that this scan is perfectly comprehensive, Emacs is a strange place.

**Comment by nickgarber** [comment]
I withdraw this request - now that I understand this package better I think my interest can be expressed using `org-babel`, `elisp`, or a combination of the two.
